authentication:
  base_url: 'https://openrouter.ai/api/v1'
  api_key: ''
llm_config:
  model: 'meta-llama/llama-3.3-8b-instruct:free'
  max_tokens: 4000
embed_config:
  model: 'sentence-transformers/all-MiniLM-l6-v2'
  model_kwargs:
    device: 'cpu'
  encode_kwargs:
    normalize_embeddings: True
retrieval_config:
  k: 3
  score_threshold: 1.2
prompt_library:
  system_prompt: |
    You are an AI assistant tasked with performing the following jobs - 

    1. Engage in general conversation with users
    2. Answer user's queries regarding their invoices/ bills information
  get_invoice_data: |
    Provided below is the data from an invoice provided by the user:
    ------------------- start of data -------------------
    {invoice_data}
    ------------------- end of data -------------------

    Extract the following details -
    1. commerce platform - website/ third party platform on which the purchase occured
    2. seller information - name, address and GST Registration Number and any other information of the seller
    3. buyer information - name, billing address, shipping address, and any other information of the buyer
    4. purchase details - order number, details of products purchased - quantity, price, etc, warranty, grand total and 
    any other information relevant to the purchase
    5. transaction currency - determine the currency used (USD, INR, etc), mention "None" if no currency information found
    6. remarks - other important remarks that could not be covered till now

    Note - Your resonse has to be strictly in a json format with the following key value pairs -

    commerce_platform: <extracted name, empty string if not found>
    seller_information: <nested dictionary with relevant information, empty string if no relevant information found>
    buyer_information: <nested dictionary with relevant information, empty string if no relevant information found>
    purchase_details: <nested dictionary with relevant information, empty string if no relevant information found>
    transaction currency: <string of currency used, "None" if not found>
    remarks: <list of relevant remarks>
  user_query:
    general_query: |
      {user_query}
      Answer in brief, providing only the information that is asked
    query_with_context: |
      Given a user query -

      ------------------- start of query -------------------
      {user_query}
      ------------------- end of query -------------------

      and additional supporting data that might be helpful in answering the query -

      ------------------- start of data -------------------
      {context}
      ------------------- end of data -------------------
      Answer the query in brief, providing only the information that is asked